### PR TITLE
Update dependencies required in README to run all the tests.

### PR DESCRIPTION
**Pull request by manisnesan**
PR to update README 
- sentencepiece is no more version constrained as per dev_requirements. 
- we don't want to spread out the dependencies in multiple places as it may likely be get out of date.

### CODE REVIEW

**Comment by manisnesan** [comment]
@muellerzr - I created this simple PR to understand first time contributor workflow.

**Comment by muellerzr** [comment]
I'd rather we state exactly how they should install it. E.g. pip install -e .[dev]

**Comment by muellerzr** [comment]
@manisnesan proposed solution I'd love to see:

- Eliminate (for now) having azureml in the dev_requirements in settings. 
- State that when building the docs, ignore errors for azure integration.

**Comment by manisnesan** [comment]
@muellerzr 
I created a new conda environment and did `pip install -e ".[dev]"` for both python versions 3.6 & 3.8. Both were successfully able to install `azureml-sdk` along with transitive dependencies (azureml-train-automl-client -> this is the one you mentioned having trouble with). Could you provide the python version you are having issues with?? 

Python 3.6
```
(azureml_test_3_6) ➜  fastai-docment-sprint git:(manisnesan_test_dep) ✗ python --version       
Python 3.6.13 :: Anaconda, Inc.

$ pip freeze | grep azure                    
azure-common==1.1.28
azure-core==1.21.1
azure-graphrbac==0.61.1
azure-identity==1.7.0
azure-mgmt-authorization==0.61.0
azure-mgmt-containerregistry==8.2.0
azure-mgmt-core==1.3.0
azure-mgmt-keyvault==9.3.0
azure-mgmt-resource==20.1.0
azure-mgmt-storage==19.0.0
azureml-automl-core==1.38.0
azureml-core==1.38.0.post2
azureml-dataprep==2.26.0
azureml-dataprep-native==38.0.0
azureml-dataprep-rslex==2.2.0
azureml-dataset-runtime==1.38.0
azureml-pipeline==1.38.0
azureml-pipeline-core==1.38.0
azureml-pipeline-steps==1.38.0
azureml-sdk==1.38.0
azureml-telemetry==1.38.0
azureml-train-automl-client==1.38.0.post2
azureml-train-core==1.38.0
azureml-train-restclients-hyperdrive==1.38.0
msrestazure==0.6.4
``` 

Python 3.8

```
(azureml_test) ➜  fastai-docment-sprint git:(manisnesan_test_dep) ✗ python --version                                   
Python 3.8.12                                                                                                          
(azureml_test) ➜  fastai-docment-sprint git:(manisnesan_test_dep) ✗ pip freeze | grep azure                                                                                                                                                   
azure-common==1.1.28                                                                                                                                                                                                                          
azure-core==1.21.1                                                                                                                                                                                                                            
azure-graphrbac==0.61.1                                                                                                                                                                                                                       
azure-identity==1.7.0                                                                                                                                                                                                                         
azure-mgmt-authorization==0.61.0                                                                                       
azure-mgmt-containerregistry==8.2.0                                                                                                                                                                                                           
azure-mgmt-core==1.3.0                                                                                                                                                                                                                        
azure-mgmt-keyvault==9.3.0                                                                                                                                                                                                                    
azure-mgmt-resource==20.1.0                                                                                                                                                                                                                   
azure-mgmt-storage==19.0.0                                                                                                                                                                                                                    
azureml-automl-core==1.38.0                                                                                                                                                                                                                   
azureml-core==1.38.0.post2                                                                                                                                                                                                                    
azureml-dataprep==2.26.0                                                                                                                                                                                                                      
azureml-dataprep-native==38.0.0                                                                                                                                                                                                               
azureml-dataprep-rslex==2.2.0                                                                                                                                                                                                                 
azureml-dataset-runtime==1.38.0                                                                                                                                                                                                               
azureml-pipeline==1.38.0                                                                                                                                                                                                                      
azureml-pipeline-core==1.38.0                                                                                                                                                                                                                 
azureml-pipeline-steps==1.38.0                                                                                                                                                                                                                
azureml-sdk==1.38.0                                                                                                                                                                                                                           
azureml-telemetry==1.38.0                                                                                                                                                                                                                     
azureml-train-automl-client==1.38.0.post2                                                                                                                                                                                                     
azureml-train-core==1.38.0                                                                                                                                                                                                                    
azureml-train-restclients-hyperdrive==1.38.0                                                                                                                                                                                                  
msrestazure==0.6.4    
```

**Comment by manisnesan** [comment]
@muellerzr - Completed the steps.

**Comment by muellerzr** [comment]
@manisnesan don't forget to also update index.ipynb, as that's what builds the README

**Comment by manisnesan** [comment]
@muellerzr - My bad. Now I know why there is a conflict.:) I will update index.original.ipynb with the changes.

**Comment by manisnesan** [comment]
Closing this PR. See https://github.com/muellerzr/fastai-docment-sprint/pull/2

**Pull request closed without merging**
